apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo  # Correção aqui
