apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: marcotfm/front:1.0
        ports:
        - containerPort: 80
