apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: marcotfm/back:1.2
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-database
              key: MYSQL_ROOT_PASSWORD
        - name: HOST
          valueFrom:
            secretKeyRef: 
              name: auth-database
              key: HOST
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: auth-database
              key: MYSQL_DATABASE
        
          


